apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  replicas : 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
      - name: mywebapp
        image: masterb3/php-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mywebappsvclb
spec:
  selector:
    app: mywebapp
  ports:
  - port: 8090
    targetPort: 80