apiVersion: apps/v1
kind: Deployment
metadata:
  name: myprofile-blue
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myprofile
      release: v1
  template:
    metadata:
      labels:
        app: myprofile
        release: v1
    spec:
      containers:
      - name: myprofile
        image: masterb3/website:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80